# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_shipping_services_response_weight_bands_item_weight_bands_item import (
    GetShippingServicesResponseWeightBandsItemWeightBandsItem,
)


class GetShippingServicesResponseWeightBandsItem(UniversalBaseModel):
    package_format: typing_extensions.Annotated[str, FieldMetadata(alias="packageFormat")]
    weight_bands: typing_extensions.Annotated[
        typing.List[GetShippingServicesResponseWeightBandsItemWeightBandsItem], FieldMetadata(alias="weightBands")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
