# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetShippingServicesResponseShippingServicesItemDropOffLocations(UniversalBaseModel):
    post_box: typing_extensions.Annotated[bool, FieldMetadata(alias="postBox")]
    parcel_box: typing_extensions.Annotated[bool, FieldMetadata(alias="parcelBox")]
    post_office: typing_extensions.Annotated[bool, FieldMetadata(alias="postOffice")]
    delivery_office: typing_extensions.Annotated[bool, FieldMetadata(alias="deliveryOffice")]
    parcelshop: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
