# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetShippingServicesResponseWeightBandsItemWeightBandsItem(UniversalBaseModel):
    max_weightin_grams: typing_extensions.Annotated[int, FieldMetadata(alias="maxWeightinGrams")]
    min_cost: typing_extensions.Annotated[float, FieldMetadata(alias="minCost")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
