# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetShippingServicesResponseShippingServicesItemPackageFormatsItemMaxDimensions(UniversalBaseModel):
    width_in_mm: typing_extensions.Annotated[int, FieldMetadata(alias="widthInMm")]
    height_in_mm: typing_extensions.Annotated[int, FieldMetadata(alias="heightInMm")]
    depth_in_mm: typing_extensions.Annotated[int, FieldMetadata(alias="depthInMm")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
