# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from . import shipping_services
from .client import AsyncMutterpedroApi, MutterpedroApi
from .environment import MutterpedroApiEnvironment
from .shipping_services import (
    GetShippingServicesResponse,
    GetShippingServicesResponseShippingServicesItem,
    GetShippingServicesResponseShippingServicesItemDropOffLocations,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItem,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemCostsItem,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemCostsItemDropOffLocations,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptions,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsParcelshop,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsParcelshopSupplementChargesItem,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsPostOffice,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsPostOfficeSupplementChargesItem,
    GetShippingServicesResponseShippingServicesItemPackageFormatsItemMaxDimensions,
    GetShippingServicesResponseWeightBandsItem,
    GetShippingServicesResponseWeightBandsItemWeightBandsItem,
)

__all__ = [
    "AsyncMutterpedroApi",
    "GetShippingServicesResponse",
    "GetShippingServicesResponseShippingServicesItem",
    "GetShippingServicesResponseShippingServicesItemDropOffLocations",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItem",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemCostsItem",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemCostsItemDropOffLocations",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptions",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsParcelshop",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsParcelshopSupplementChargesItem",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsPostOffice",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemDropOffOptionsPostOfficeSupplementChargesItem",
    "GetShippingServicesResponseShippingServicesItemPackageFormatsItemMaxDimensions",
    "GetShippingServicesResponseWeightBandsItem",
    "GetShippingServicesResponseWeightBandsItemWeightBandsItem",
    "MutterpedroApi",
    "MutterpedroApiEnvironment",
    "shipping_services",
]
